AspNetMvcBlog/App.Web.Mvc/Models/ErrorViewModel.cs
namespace App.Web.Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspNetMvcBlog/App.Web.Mvc/Models/SliderViewModel.cs
namespace App.Web.Mvc.Models
{
	public class SliderViewModel
	{
		public string? Name { get; set; }
		public string? Title { get; set; }
		public string? ImageUrl { get; set; }
		public DateTime Date { get; set; }
	}
}

AspNetMvcBlog/App.Web.Mvc/Controllers/Admin/AdminBlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Controllers.Admin
{
    public class AdminBlogController : BaseAdminController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
    
}

AspNetMvcBlog/App.Web.Mvc/Controllers/Admin/AdminHomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Controllers.Admin
{
    public class AdminHomeController : BaseAdminController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetMvcBlog/App.Web.Mvc/Controllers/Admin/AdminPageController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Controllers.Admin
{
    public class AdminPageController : BaseAdminController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetMvcBlog/App.Web.Mvc/Controllers/Admin/AdminSettingController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Controllers.Admin
{
    public class AdminSettingController : BaseAdminController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetMvcBlog/App.Web.Mvc/Controllers/Admin/AdminUserController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Controllers.Admin
{
    public class AdminUserController : BaseAdminController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetMvcBlog/App.Web.Mvc/Controllers/Admin/BaseAdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Controllers.Admin
{
    public abstract class BaseAdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetMvcBlog/App.Web.Mvc/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Register()
        {

            return View();
        }
        public IActionResult Login(string redirectUrl)
        {
            return View();
        }
        public IActionResult ForgotPassword()
        {
            return View();
        }
    }
}

AspNetMvcBlog/App.Web.Mvc/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Search(string query, int page)
        {
            return View();
        }
        public IActionResult Detail(int id) 
        {
            return View();
        }
    }
}

AspNetMvcBlog/App.Web.Mvc/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Controllers
{
    public class CategoryController : Controller
    {
        public IActionResult Travel(int id, int page)
        {
            return View();
        }
        public IActionResult Software(int id, int page)
        {
            return View();
        }
        public IActionResult Lifestyle(int id, int page)
        {
            return View();
        }
        public IActionResult Explore(int id, int page)
        {
            return View();
        }
    }
}

AspNetMvcBlog/App.Web.Mvc/Controllers/HomeController.cs
using App.Web.Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace App.Web.Mvc.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Index2()
        {
            return View();
        }
        public IActionResult Index3()
        {
            return View();
        }
    }
}

AspNetMvcBlog/App.Web.Mvc/Controllers/PageController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.Controllers
{
    public class PageController : Controller
    {
        public IActionResult Detail(int id)
        {
            return View();
        }
    }
}

AspNetMvcBlog/App.Web.Mvc/ViewComponents/AboutViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.ViewComponents
{
	public class AboutViewComponent: ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			return View();
		}
	}
}

AspNetMvcBlog/App.Web.Mvc/ViewComponents/BlogDetailsViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.ViewComponents
{
	public class BlogDetailsViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			return View();
		}
	}
}

AspNetMvcBlog/App.Web.Mvc/ViewComponents/BlogSearchViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.ViewComponents
{
	public class BlogSearchViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			return View();
		}
	}
}

AspNetMvcBlog/App.Web.Mvc/ViewComponents/CategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.ViewComponents
{
	public class CategoryViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			return View();
		}
	}
}

AspNetMvcBlog/App.Web.Mvc/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.ViewComponents
{
	public class FooterViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			return View();
		}
	}
}

AspNetMvcBlog/App.Web.Mvc/ViewComponents/NavbarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.ViewComponents
{
	public class NavbarViewComponent: ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			return View();
		}
	}
}

AspNetMvcBlog/App.Web.Mvc/ViewComponents/SliderViewComponent.cs
using App.Web.Mvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace App.Web.Mvc.ViewComponents
{
    public class SliderViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var slider = new List<SliderViewModel>
            {
                new SliderViewModel
                {
                    Date = DateTime.Now,
                    Name = "Our Favorite Weekend Getaways",
                    Title= "Software",
                    ImageUrl= "/images/slider/slider2.jpg"
                },
                new SliderViewModel
                {
                    Date = DateTime.Now,
                    Name = "Trip to California",
                    Title= "Travel",
                    ImageUrl= "/images/slider/slider1.jpg"
                },
                new SliderViewModel
                {
                    Date = DateTime.Now,
                    Name = "Tips for Taking a Long-term Trip",
                    Title= "LifeStyle",
                    ImageUrl= "/images/slider/slider3.jpg"
                },
                new SliderViewModel
                {
                    Date = DateTime.Now,
                    Name = "Tips for Taking a Long-term Trip",
                    Title= "LifeStyle",
                    ImageUrl= "/images/slider/slider1.jpg"
                },
                new SliderViewModel
                {
                    Date = DateTime.Now,
                    Name = "Tips for Taking a Long-term Trip",
                    Title= "LifeStyle",
                    ImageUrl= "/images/slider/slider2.jpg"
                },
            };

            return View(slider);
        }
    }
}

AspNetMvcBlog/App.Web.Mvc/Views/Page/Detail.cshtml
@await Component.InvokeAsync("About");

AspNetMvcBlog/App.Web.Mvc/Views/Shared/Components/About/Default.cshtml
<partial name="_PartialSearch" />
<div class="breadcrumb-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="text-center">
                    <h2 class="lg-title">About Me</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="pt-5 padding-bottom">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-lg-12">
                        <img src="~/images/about.jpg" alt="" class="img-fluid w-100">
                    </div>
                </div>
                <div class="row justify-content-center mt-5">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-4">
                                <h5 class="text-uppercase letter-spacing mb-4">Who is me?</h5>
                                <p>Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat</p>
                            </div>
                            <div class="col-lg-4">
                                <h5 class="text-uppercase letter-spacing mb-4">My vission</h5>
                                <p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis biben. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit.</p>
                            </div>
                            <div class="col-lg-4">
                                <h5 class="text-uppercase letter-spacing mb-4">Follow Me :</h5>
                                <div class="follow-socials">
                                    <a href="#" class="fb"><i class="ti-facebook"></i></a>
                                    <a href="#" class="twt"><i class="ti-twitter"></i></a>
                                    <a href="#" class="inst"><i class="ti-instagram"></i></a>
                                    <a href="#" class="youtube"><i class="ti-youtube"></i></a>
                                    <a href="#" class="pint"><i class="ti-pinterest"></i></a>
                                </div>
                            </div>
                        </div>
                        <h3 class="mb-3 mt-5">I have travel 10+ more countries in this year.</h3>
                        <p class="mb-5">Poor Alice! It was as much as she could do, lying down on one side, to look through into the garden with one eye; but to get through was more hopeless than ever: she sat down and began to cry again.</p>
                        <div class="row">
                            <div class="col-lg-3 col-md-6">
                                <div class="about-widget mb-4 mb-lg-0">
                                    <img src="~/images/news/news-1.jpg" alt="" class="img-fluid">
                                    <h4 class="mt-3">Hill ward</h4>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-6">
                                <div class="about-widget mb-4 mb-lg-0">
                                    <img src="~/images/news/news-2.jpg" alt="" class="img-fluid">
                                    <h4 class="mt-3">Awesome ride</h4>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-6">
                                <div class="about-widget mb-4 mb-lg-0">
                                    <img src="~/images/news/news-3.jpg" alt="" class="img-fluid">
                                    <h4 class="mt-3">Newyork</h4>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-6">
                                <div class="about-widget mb-4 mb-lg-0">
                                    <img src="~/images/news/news-4.jpg" alt="" class="img-fluid">
                                    <h4 class="mt-3">Rising Sea</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

AspNetMvcBlog/App.Web.Mvc/Views/Shared/Components/Navbar/Default.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Revolve - Personal Magazine blog Template</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!--Favicon-->
	<link rel="shortcut icon" href="~/images/favicon.ico" type="image/x-icon">

	<!-- THEME CSS
	================================================== -->
	<!-- Bootstrap -->
	<link rel="stylesheet" href="~/plugins/bootstrap/css/bootstrap.min.css">
	<!-- Themify -->
	<link rel="stylesheet" href="~/plugins/themify/css/themify-icons.css">
	<link rel="stylesheet" href="~/plugins/slick-carousel/slick-theme.css">
	<link rel="stylesheet" href="~/plugins/slick-carousel/slick.css">
	<!-- Slick Carousel -->
	<link rel="stylesheet" href="~/plugins/owl-carousel/owl.carousel.min.css">
	<link rel="stylesheet" href="~/plugins/owl-carousel/owl.theme.default.min.css">
	<link rel="stylesheet" href="~/plugins/magnific-popup/magnific-popup.css">
	<!-- manin stylesheet -->
	<link rel="stylesheet" href="~/css/style.css">
</head>

<div class="header-logo py-5 d-none d-lg-block">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-6 text-center">
				<a class="navbar-brand" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" alt="" class="img-fluid w-100"></a>
			</div>
		</div>
	</div>
</div>

<header class="header-top bg-grey justify-content-center">
	<nav class="navbar navbar-expand-lg navigation">
		<div class="container">
			<a class="navbar-brand d-lg-none" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" alt="" class="img-fluid"></a>

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="ti-menu"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarContent">
				<ul id="menu" class="menu navbar-nav ">
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" asp-controller="Home" asp-action="Index">
							Home
						</a>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Blog Posts
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown2">
							<a asp-controller="Blog" asp-action="Search">SEARCH</a>
							<a asp-controller="Blog" asp-action="Detail">DETAILS</a>
						</div>
					</li>

					<li class="nav-item"><a asp-controller="Page" asp-action="Detail" class="nav-link">About</a></li>

					<li class="nav-item dropdown">
						<a asp-controller="Category" asp-action="Travel" class="nav-link">Category</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown2">
							<a asp-controller="Category" asp-action="Travel">Travel</a>
							<a asp-controller="Category" asp-action="Software">Software</a>
							<a asp-controller="Category" asp-action="Lifestyle">Lifestyle</a>
							<a asp-controller="Category" asp-action="Explore">Explore</a>
						</div>
					</li>

						@*<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Post Formats
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown3">
					<a class="dropdown-item" href="~/post-video.html">Video Formats</a>
					<a class="dropdown-item" href="~/post-audio.html">Audio Format</a>
					<a class="dropdown-item" href="~/post-link.html">Quote Format</a>
					<a class="dropdown-item" href="~/post-gallery.html">Gallery Format</a>
					<a class="dropdown-item" href="~/post-image.html">Image Format</a>
					</div>
					</li>*@

					<li class="nav-item dropdown">
						<a asp-controller="Auth" asp-action="Register" class="nav-link">Contact</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown2">
							<a asp-controller="Auth" asp-action="Login">Login</a>
							<a asp-controller="Auth" asp-action="Register">Register</a>
						</div>
					</li>

					<li class="nav-item d-lg-none">
						<div class="search_toggle p-3 d-inline-block bg-white"><i class="ti-search"></i></div>
					</li>
				</ul>
			</div>

			<div class="text-right search d-none d-lg-block">
				<div class="search_toggle"><i class="ti-search"></i></div>
			</div>
			<div class="search-wrap">
				<div class="overlay">
					<form method="post" asp-controller="Blog" asp-action="Search" class="search-form">
						<div class="container">
							<div class="row">
								<div class="col-md-10 col-9">
									<input type="text" class="form-control" placeholder="Search..." />
								</div>
								<div class="col-md-2 col-3 text-right">
									<div class="search_toggle toggle-wrap d-inline-block">
										<i class="ti-close"></i>
									</div>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</nav>
</header>

AspNetMvcBlog/App.Web.Mvc/Views/Shared/PartialFooterSaf.cshtml
	<!--footer start-->
<footer class="footer-section bg-grey">
	<div class="instagram-photo-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<h4 class="text-center">Follow in Instagram</h4>
				</div>
			</div>

			<div class="row no-gutters" id="instafeed">
			</div>
		</div>
	</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<div class="mb-4">
					<h2 class="footer-logo">Revolve.</h2>
				</div>
				<ul class="list-inline footer-socials">
					<li class="list-inline-item"><a href="#"><i class="ti-facebook mr-2"></i>Facebook</a></li>
					<li class="list-inline-item"><a href="#"><i class="ti-twitter mr-2"></i>Twitter</a></li>
					<li class="list-inline-item"><a href="#"><i class="ti-linkedin mr-2"></i>Linkedin</a></li>
					<li class="list-inline-item"><a href="#"><i class="ti-pinterest mr-2"></i>Pinterest</a></li>
					<li class="list-inline-item"><a href="#"><i class="ti-github mr-2"></i>Github</a></li>
					<li class="list-inline-item"><a href="#"><i class="ti-instagram mr-2"></i>Instrgram</a></li>
					<li class="list-inline-item"><a href="#"><i class="ti-rss mr-2"></i>rss</a></li>
				</ul>
			</div>

			<div class="col-md-12 text-center">
				<p class="copyright">© Copyright 2019 - Revolve. All Rights Reserved.</p>
			</div>
		</div>
	</div>
</footer>
<!--footer end-->

AspNetMvcBlog/App.Web.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Revolve - Personal Magazine blog Template</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--Favicon-->
    <link rel="shortcut icon" href="~/images/favicon.ico" type="image/x-icon">
    <!-- THEME CSS
    ================================================== -->
    <!-- Bootstrap -->

    <link rel="stylesheet" href="~/plugins/bootstrap/css/bootstrap.min.css">
    <!-- Themify -->
    <link rel="stylesheet" href="~/plugins/themify/css/themify-icons.css">
    <link rel="stylesheet" href="~/plugins/slick-carousel/slick-theme.css">
    <link rel="stylesheet" href="~/plugins/slick-carousel/slick.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- Slick Carousel -->
    <link rel="stylesheet" href="~/plugins/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/plugins/owl-carousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/plugins/magnific-popup/magnific-popup.css">
    <!-- manin stylesheet -->
    <link rel="stylesheet" type="text/css" href="~/css/StyleSheet.css">
    <link rel="stylesheet" href="~/css/style.css">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
</head>
<body>


	@await Component.InvokeAsync("Navbar")

	@RenderBody()

	@await Component.InvokeAsync("Footer")

	<script src="~/plugins/jquery/jquery.js"></script>
	<!-- Bootstrap jQuery -->
	<script src="~/plugins/bootstrap/js/bootstrap.min.js"></script>
	<script src="~/plugins/bootstrap/js/popper.min.js"></script>
	<!-- Owl caeousel -->
	<script src="~/plugins/owl-carousel/owl.carousel.min.js"></script>
	<script src="~/plugins/slick-carousel/slick.min.js"></script>
	<script src="~/plugins/magnific-popup/magnific-popup.js"></script>
	<!-- Instagram Feed Js -->
	<script src="~/plugins/instafeed-js/instafeed.min.js"></script>
	<script src="~/plugins/google-map/gmap.js"></script>
	<!-- main js -->
	<script src="~/js/custom.js"></script>
</body>
</html>

AspNetMvcBlog/App.Web.Mvc/Views/Shared/_PartialSearch.cshtml
<div class="search-wrap">
    <div class="overlay">
        <form method="post" asp-controller="Blog" asp-action="Search" class="search-form">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-9">
                        <input type="text" class="form-control" placeholder="Search..."/>
                    </div>
                    <div class="col-md-2 col-3 text-right">
                        <div class="search_toggle toggle-wrap d-inline-block">
                            <i class="ti-close"></i>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>